// Auto-generated imports for command implementations
package main

import (
	// Test runner adapters (self-register via init)
	_ "github.com/ready-to-release/eac/go/adapters/cucumber"
	_ "github.com/ready-to-release/eac/go/adapters/godog"  // registers godog descriptor
	_ "github.com/ready-to-release/eac/go/adapters/gotest" // registers GoTestRunner + gotest descriptor
	_ "github.com/ready-to-release/eac/go/adapters/mocha"

	_ "github.com/ready-to-release/eac/go/cli/eac/impl/build"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/create/commit-message"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/create/design"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/create/risk-assess"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/create/risk-profile"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/create/spec"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/create/squash-message"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/describe"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/design"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/drawio"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/extension"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/get"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/help"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/init"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/lint"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/list"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/pipeline"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/pipeline/ci"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/release"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/scan"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/scan/zap"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/serve"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/serve/design"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/serve/gource"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/show"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/specs"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/specs/unused"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/templates"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/templates/install/ai"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/templates/install/claude"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/templates/install/docs"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/templates/install/reports"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/templates/install/specs"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/test"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/update/ai-summary"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/update/cache-clear"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/update/design"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/update/docs"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/update/docs-manifest"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/update/evidence"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/update/go-mod-sums"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/update/go-tidy"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/update/pdf-screenshots"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/update/structurizr"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/validate"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/validate/risk-catalog"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/validate/risk-profile"
	_ "github.com/ready-to-release/eac/go/cli/eac/impl/work"
)
