package generation

import (
	"context"
	"fmt"
	"os"

	ai "github.com/ready-to-release/eac/contracts/ai-provider/0.1.0"
	"github.com/ready-to-release/eac/go/core/validation"
	"go.uber.org/zap"
)

// StructuredGenerator handles AI generation of structured output with validation
// Generates content in specified format (JSON, Gherkin, OSCAL, Structurizr DSL)
// Commands handle deterministic formatting of the generated output
//
// IMPORTANT: This is a CORE library and must NOT use component loggers (logging.C()).
// All logging must go through the Logger field, which should be zap.NewNop() by default.
type StructuredGenerator struct {
	// Generation configuration
	OutputFormat StructuredFormat
	Executor     ai.GenerationExecutor
	Validator    validation.Validator

	// Retry configuration
	MaxAttempts int
	Strategy    RetryStrategy
	Debug       bool
	Logger      *zap.Logger // Should be zap.NewNop() to prevent writing to command logs
}

// GenerationResult contains results from AI generation.
type GenerationResult struct {
	GeneratedContent string                       // Content generated by AI (validated against schema)
	FormattedContent string                       // Same as GeneratedContent (commands handle formatting)
	Attempts         int                          // Number of generation attempts
	Valid            bool                         // Whether generation succeeded
	Errors           []validation.ValidationError // Validation errors (if any)
}

// generationConfig holds configuration for generation with retry.
type generationConfig struct {
	name           string
	executor       ai.GenerationExecutor
	validator      validation.Validator
	initialPrompt  string
	originalPrompt string // Base prompt for retry construction
}

// generationResult holds the outcome of generation.
type generationResult struct {
	output   string
	attempts int
	errors   []validation.ValidationError
}

// Generate performs AI generation with internal retry logic and format awareness.
func (g *StructuredGenerator) Generate(ctx context.Context, prompt string) (*GenerationResult, error) {
	g.log("Starting structured content generation")

	strategy := g.getStrategy()

	// Generate structured content in specified format
	g.logf("Generating structured content", zap.String("format", string(g.OutputFormat)))

	// Get format-specific instruction
	formatInstruction, err := GetPhaseInstruction(g.OutputFormat)
	if err != nil {
		return &GenerationResult{
			Valid:  false,
			Errors: []validation.ValidationError{*validation.NewValidationError(validation.ErrUnsupportedFormat, err.Error(), 0)},
		}, fmt.Errorf("unsupported output format: %w", err)
	}

	generationPrompt := prompt + "\n\n" + formatInstruction

	result, err := g.runGeneration(ctx, strategy, generationConfig{
		name:           "generation",
		executor:       g.Executor,
		validator:      g.Validator,
		initialPrompt:  generationPrompt,
		originalPrompt: generationPrompt,
	})
	if err != nil {
		return &GenerationResult{
			GeneratedContent: result.output,
			Attempts:         result.attempts,
			Valid:            false,
			Errors:           result.errors,
		}, fmt.Errorf("failed to generate valid content after %d attempts: %w", result.attempts, err)
	}

	// Generation complete - commands will handle formatting
	g.log("Generation complete - returning validated content")

	return &GenerationResult{
		GeneratedContent: result.output,
		FormattedContent: result.output, // Same as generated output
		Attempts:         result.attempts,
		Valid:            true,
		Errors:           nil,
	}, nil
}

// runGeneration executes generation with retry logic.
func (g *StructuredGenerator) runGeneration(ctx context.Context, strategy RetryStrategy, cfg generationConfig) (generationResult, error) {
	currentPrompt := cfg.initialPrompt
	var lastOutput string
	var lastErrors []validation.ValidationError

	// Log debug flag state
	g.logf("Starting generation loop", zap.Bool("debug", g.Debug), zap.Int("maxAttempts", g.MaxAttempts))

	for attempt := 1; attempt <= g.MaxAttempts; attempt++ {
		output, err := cfg.executor.Execute(ctx, currentPrompt)
		if err != nil {
			return generationResult{attempts: attempt}, fmt.Errorf("AI execution failed, attempt %d: %w", attempt, err)
		}

		// Clean up output based on format (remove markdown fences, etc.)
		cleanedOutput := g.cleanupOutput(output, g.OutputFormat)

		// Log the FULL AI output for debugging
		g.logf("AI generated output",
			zap.Int("attempt", attempt),
			zap.Int("outputLength", len(cleanedOutput)))

		// Log the full output as a separate entry so it appears in the log file
		g.logf("Full AI output", zap.String("content", cleanedOutput))

		// Print full output to stderr if debug is enabled
		if g.Debug {
			fmt.Fprintf(os.Stderr, "\nDEBUG: Full AI output (attempt %d/%d):\n", attempt, g.MaxAttempts)
			fmt.Fprintf(os.Stderr, "---BEGIN AI OUTPUT---\n%s\n---END AI OUTPUT---\n\n", cleanedOutput)
		}

		errors := cfg.validator.Validate(cleanedOutput, map[string]interface{}{
			"attempt": attempt,
		})

		if len(errors) == 0 {
			g.logf("Generation complete", zap.Int("attempts", attempt))
			return generationResult{output: cleanedOutput, attempts: attempt, errors: nil}, nil
		}

		lastOutput = cleanedOutput
		lastErrors = errors

		if !g.canRetry(ctx, strategy, errors, attempt) {
			break
		}

		g.logWarn("Validation failed, retrying",
			zap.Int("attempt", attempt),
			zap.Int("errorCount", len(errors)),
			zap.Bool("debugEnabled", g.Debug))

		// Log detailed error messages if debug is enabled
		// ALWAYS log the first few errors to help with debugging
		for i, err := range errors {
			if i >= 5 {
				g.logWarn("Additional validation errors truncated", zap.Int("remaining", len(errors)-i))
				break
			}

			errorCode := ""
			if err.Code != nil {
				errorCode = err.Code.Code
			}

			g.logWarn("Validation error",
				zap.Int("errorNum", i+1),
				zap.String("code", errorCode),
				zap.String("message", err.Message))

			// Print to stderr if debug is enabled
			if g.Debug {
				fmt.Fprintf(os.Stderr, "  Validation error %d [%s]: %s\n", i+1, errorCode, err.Message)
			}
		}

		// Print debug header if debug is enabled
		if g.Debug {
			fmt.Fprintf(os.Stderr, "DEBUG: Validation failed (attempt %d/%d) with %d errors\n", attempt, g.MaxAttempts, len(errors))
		}

		currentPrompt = strategy.BuildRetryPrompt(ctx, cfg.originalPrompt, output, errors, attempt)
	}

	return generationResult{output: lastOutput, attempts: g.MaxAttempts, errors: lastErrors}, fmt.Errorf("validation failed")
}

// canRetry checks if another retry attempt is allowed.
func (g *StructuredGenerator) canRetry(ctx context.Context, strategy RetryStrategy, errors []validation.ValidationError, attempt int) bool {
	return attempt < g.MaxAttempts && strategy.ShouldRetry(ctx, errors, attempt, g.MaxAttempts)
}

// cleanupOutput removes common AI output artifacts based on format.
func (g *StructuredGenerator) cleanupOutput(output string, format StructuredFormat) string {
	switch format {
	case FormatJSON, FormatOSCALCatalog, FormatOSCALProfile:
		return stripMarkdownFences(output)
	default:
		return output
	}
}

// stripMarkdownFences removes markdown code fences from output.
func stripMarkdownFences(content string) string {
	// Remove ```json\n...\n``` or ```\n...\n```
	if len(content) > 6 && content[0:3] == "```" {
		// Find the first newline after ```
		start := 3
		for start < len(content) && content[start] != '\n' {
			start++
		}
		if start < len(content) {
			start++ // Skip the newline
		}

		// Find the closing ```
		end := len(content)
		if lastFence := lastIndex(content, "```"); lastFence > start {
			end = lastFence
		}

		// Remove any trailing whitespace before the closing fence
		for end > start && (content[end-1] == '\n' || content[end-1] == ' ' || content[end-1] == '\t') {
			end--
		}

		return content[start:end]
	}
	return content
}

// lastIndex finds the last occurrence of substr in s.
func lastIndex(s, substr string) int {
	for i := len(s) - len(substr); i >= 0; i-- {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}

// getStrategy returns the configured strategy or the default.
func (g *StructuredGenerator) getStrategy() RetryStrategy {
	if g.Strategy != nil {
		return g.Strategy
	}
	return &StandardStrategy{}
}

// log writes an info message if logger is configured
// Logs are discarded if Logger is nil or zap.NewNop().
func (g *StructuredGenerator) log(msg string) {
	if g.Logger != nil {
		g.Logger.Info(msg)
	}
}

// logf writes an info message with fields if logger is configured
// Logs are discarded if Logger is nil or zap.NewNop().
func (g *StructuredGenerator) logf(msg string, fields ...zap.Field) {
	if g.Logger != nil {
		g.Logger.Info(msg, fields...)
	}
}

// logWarn writes a warning message with fields if logger is configured
// Logs are discarded if Logger is nil or zap.NewNop().
func (g *StructuredGenerator) logWarn(msg string, fields ...zap.Field) {
	if g.Logger != nil {
		g.Logger.Warn(msg, fields...)
	}
}
