@deps:go @L2 @ov
Feature: eac-commands_books

  As a documentation maintainer
  I want to build books that aggregate static and generated content
  So that I can produce comprehensive documentation with up-to-date reference material

  # ============================================================================
  # Configuration Commands - Run against real repository
  # ============================================================================

  Rule: Books configuration must be discoverable

    Scenario: Show configured books
      When I run the command "show books"
      Then the exit code is 0
      And I should see "docs" in the output
      And I should see a table with book information

  Rule: Books configuration must be validated

    Scenario: Validate valid books.yml
      When I run the command "validate books"
      Then the exit code is 0
      And I should see "valid" or "success"

  # ============================================================================
  # Build Output Verification - Depends on pre-built modules
  # Staging directories are named by book name: site, repository-report
  # ============================================================================

  @depm:docs
  Rule: Copy sources must copy static files to staging

    # Site book (docs module) uses copy and inline sources
    Scenario: Staging contains copied markdown files
      Given the "docs" module has been built
      Then build output "site/staging" contains "**/*.md" files
      And directory structure is preserved from source

    Scenario: Staging contains nav files
      Given the "docs" module has been built
      Then build output "site/staging" contains ".nav.yml" files

    Scenario: Staging contains assets
      Given the "docs" module has been built
      Then build output "site/staging/assets" directory exists

  @depm:books
  Rule: Command sources must generate new files

    # Repository-report book (books module) uses command sources
    Scenario: Generated file from show modules command exists
      Given the "books" module has been built
      Then build output "repository-report/staging/modules.md" exists
      And the file contains "|"

    Scenario: Generated file includes frontmatter
      Given the "books" module has been built
      Then build output "repository-report/staging/modules.md" contains "---"
      And the file contains "title:"

    Scenario: Generated file includes generation metadata
      Given the "books" module has been built
      Then build output "repository-report/staging/modules.md" contains "Generated by:"

  @depm:books
  Rule: Navigation must be generated for new sections

    Scenario: Nav file generated for command section
      Given the "books" module has been built
      Then build output "repository-report/staging/.nav.yml" exists

  @depm:docs
  Rule: Book build must produce MkDocs site

    Scenario: Build output contains HTML site
      Given the "docs" module has been built
      Then build output "docs/site/index.html" exists

  @depm:docs
  Rule: Book preprocessing must be transparent

    Scenario: Build log shows preprocessing was triggered
      Given the "docs" module has been built
      Then build log "docs/build.log" contains "Book" or "preprocessing"
