@deps:go @L2 @ov
Feature: eac-commands_books

  As a documentation maintainer
  I want to build books that aggregate static and generated content
  So that I can produce comprehensive documentation with up-to-date reference material

  # ============================================================================
  # Configuration Commands - No build dependency needed
  # ============================================================================

  Rule: Books configuration must be discoverable

    Scenario: Show configured books
      When I run the command "show books"
      Then the exit code is 0
      And I should see "docs" in the output
      And I should see a table with book information

    @isolated
    Scenario: Show books when none configured
      Given books.yml does not exist
      When I run the command "show books"
      Then the exit code is 0
      And I should see "No books" or "empty"

  Rule: Books configuration must be validated

    Scenario: Validate valid books.yml
      When I run the command "validate books"
      Then the exit code is 0
      And I should see "valid" or "success"

    @isolated
    Scenario: Validate detects missing module
      Given books.yml references module "nonexistent"
      When I run the command "validate books"
      Then the exit code is 1
      And I should see "not found" or "Error"

    @isolated
    Scenario: Validate detects invalid command
      Given books.yml has inline source with command "nonexistent-command"
      When I run the command "validate books"
      Then the exit code is 1
      And I should see "Unknown command" or "unknown"

  # ============================================================================
  # Build Output Verification - Depends on pre-built docs module
  # ============================================================================

  @depm:docs
  Rule: Copy sources must copy static files to staging

    Scenario: Staging contains copied markdown files
      Given the "docs" module has been built
      Then build output "docs/staging" contains "**/*.md" files
      And directory structure is preserved from source

    Scenario: Staging contains nav files
      Given the "docs" module has been built
      Then build output "docs/staging" contains ".nav.yml" files

    Scenario: Staging contains assets
      Given the "docs" module has been built
      Then build output "docs/staging/assets" directory exists

  @depm:docs
  Rule: Command sources must generate new files

    Scenario: Generated file from show modules command exists
      Given the "docs" module has been built
      Then build output "docs/staging/reference/generated/modules.md" exists
      And the file contains "|"

    Scenario: Generated file includes frontmatter
      Given the "docs" module has been built
      Then build output "docs/staging/reference/generated/modules.md" contains "---"
      And the file contains "title:"

    Scenario: Generated file includes generation metadata
      Given the "docs" module has been built
      Then build output "docs/staging/reference/generated/modules.md" contains "Generated by:"

  @depm:docs
  Rule: Navigation must be generated for new sections

    Scenario: Nav file generated for command section
      Given the "docs" module has been built
      Then build output "docs/staging/reference/generated/.nav.yml" exists

  @depm:docs
  Rule: Book build must produce MkDocs site

    Scenario: Build output contains HTML site
      Given the "docs" module has been built
      Then build output "docs/site/index.html" exists

  # ============================================================================
  # Build Log Verification - Check preprocessing messages in build output
  # ============================================================================

  @depm:docs
  Rule: Book preprocessing must be transparent

    Scenario: Build log shows preprocessing was triggered
      Given the "docs" module has been built
      Then build log "docs/build.log" contains "Book" or "preprocessing"
