@deps:go @L2 @ov
Feature: eac-commands_books

  As a documentation maintainer
  I want to build books that aggregate static and generated content
  So that I can produce comprehensive documentation with up-to-date reference material

  Background:
    Given a repository with books.yml configuration
    And the docs module is of type mkdocs-site

  Rule: Books configuration must be discoverable

    Scenario: Show configured books
      When I run the command "show books"
      Then the exit code is 0
      And I should see "docs" in the output
      And I should see a table with book information

    Scenario: No books configured
      Given books.yml does not exist
      When I run the command "show books"
      Then the exit code is 0
      And I should see "No books configured" or "empty"

  Rule: Books configuration must be validated

    Scenario: Validate valid books.yml
      When I run the command "validate books"
      Then the exit code is 0
      And I should see "valid" or "success"

    Scenario: Validate detects missing module
      Given books.yml references module "nonexistent"
      When I run the command "validate books"
      Then the exit code is 1
      And I should see "not found" or "Error"

    Scenario: Validate detects invalid command
      Given books.yml has inline source with command "nonexistent-command"
      When I run the command "validate books"
      Then the exit code is 1
      And I should see "unknown command" or "not found"

  Rule: Copy sources must copy static files to staging

    Scenario: Copy markdown files to staging
      When I build book "docs"
      Then staging directory contains files from "docs/**/*.md"
      And directory structure is preserved

    Scenario: Copy nav files to staging
      When I build book "docs"
      Then staging directory contains ".nav.yml" files
      And nav files match source structure

    Scenario: Copy assets to staging
      When I build book "docs"
      Then staging directory contains "assets/" directory
      And asset files are copied

  Rule: Command sources must generate new files

    Scenario: Generate file from show modules command
      When I build book "docs"
      Then staging contains "reference/generated/modules.md"
      And the file contains module table output

    Scenario: Generated file includes frontmatter
      When I build book "docs"
      Then "reference/generated/modules.md" has YAML frontmatter
      And frontmatter contains "title"

    Scenario: Generated file includes generation metadata
      When I build book "docs"
      Then "reference/generated/modules.md" contains "Generated by"

  Rule: Inline sources must insert content at markers

    Scenario: Insert content at marker position
      Given source file "index.md" contains "<!-- book:insert modules-overview -->"
      When I build book "docs"
      Then staging "index.md" contains module table output
      And the marker is replaced with generated content

    Scenario: Wrap inserted content with generation markers
      Given source file "index.md" contains "<!-- book:insert modules-overview -->"
      When I build book "docs"
      Then staging "index.md" contains "<!-- book:generated modules-overview -->"
      And staging "index.md" contains "<!-- /book:generated -->"

    Scenario: Unknown marker is left unchanged
      Given source file contains "<!-- book:insert unknown-marker -->"
      And books.yml does not define "unknown-marker"
      When I build book "docs"
      Then the marker remains unchanged in output

    Scenario: Custom marker pattern is supported
      Given books.yml defines custom marker_pattern
      And source file uses custom marker format
      When I build book "docs"
      Then custom markers are replaced with content

  Rule: Navigation must be generated for new sections

    Scenario: Generate nav.yml for generated section
      When I build book "docs"
      Then staging contains "reference/generated/.nav.yml"
      And nav.yml lists generated files

    Scenario: Insert generated section into parent nav
      When I build book "docs"
      Then staging "reference/.nav.yml" includes "generated"
      And section is inserted at configured position

  Rule: Book build must produce MkDocs site

    Scenario: Build book produces HTML site
      When I run the command "build docs"
      Then the exit code is 0
      And output directory contains "site/index.html"

    Scenario: Build book with PDF option
      When I run the command "build docs --pdf"
      Then the exit code is 0
      And output directory contains PDF files

  Rule: Book preprocessing must be transparent

    Scenario: Build command auto-detects books.yml
      Given books.yml exists for module "docs"
      When I run the command "build docs"
      Then book preprocessing is triggered
      And I should see "Book configuration found" or "preprocessing"

    Scenario: Build without books.yml uses standard mkdocs
      Given books.yml does not exist
      When I run the command "build docs"
      Then standard mkdocs build is used
      And no preprocessing occurs
