#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Import the CommandRunner module and create top-level command aliases

.DESCRIPTION
    This script imports the go.psm1 module with -Force and creates session-wide aliases
    for all top-level commands (show, list, describe, commit, etc.).
    The aliases are temporary and only last for the current PowerShell session.

    Welcome messages are shown only once per session (tracked via $env:CMD_ALIASES_EMITTED).

.PARAMETER NoAlias
    Skip creating command aliases. Use this if you only want the module functions.

.EXAMPLE
    .\importer.ps1
    show files
    list commands

.EXAMPLE
    .\importer.ps1 -NoAlias
    Invoke-GoSrcCommand show files

.NOTES
    Can be executed directly (.\importer.ps1) or dot-sourced (. .\importer.ps1).
    Global scope functions are created, so aliases persist in your session either way.
#>

[CmdletBinding()]
param(
    [switch]$NoAlias
)

$ErrorActionPreference = "Stop"

# Clear cache to force refresh
$env:SRC_COMMANDS_DESCRIBE = $null

# Get the module path
$ModulePath = Join-Path $PSScriptRoot "scripts\pwsh\go-invoker\go.psm1"

# Check if module exists
if (-not (Test-Path $ModulePath)) {
    Write-Error "Module not found at: $ModulePath"
    exit 1
}

# Import the module with -Force to reload if already loaded
Import-Module $ModulePath -Force

Write-Host "✅ CommandRunner module imported successfully!" -ForegroundColor Green

# Create ai-provider.personal.yml for local development with claude-cli
$PersonalConfigPath = Join-Path $PSScriptRoot ".eac\ai-provider.personal.yml"
if (-not (Test-Path $PersonalConfigPath)) {
    # Ensure directory exists
    $PersonalConfigDir = Split-Path $PersonalConfigPath -Parent
    if (-not (Test-Path $PersonalConfigDir)) {
        New-Item -Path $PersonalConfigDir -ItemType Directory -Force | Out-Null
    }

    # Create config with claude-cli provider
    $ConfigContent = @"
# EAC Configuration (Personal - Local Development)
# Generated by: importer.ps1
# Uses Claude CLI with your subscription (no API costs)
# GITIGNORED: Do not commit

ai:
  provider: claude-cli
  model: claude-3-haiku-20240307

git:
  token: ""
"@

    Set-Content -Path $PersonalConfigPath -Value $ConfigContent -Encoding UTF8
    Write-Host "✅ Created local AI config with claude-cli provider" -ForegroundColor Green
    Write-Host "   File: .eac\ai-provider.personal.yml" -ForegroundColor Gray
}

# Create clie alias pointing to the OS-specific binary
# Binary is now at out/build/clie/go/ (component-level output structure)
$ClieBinaryPath = Join-Path $PSScriptRoot "out\build\clie\go-go"
if ($IsWindows -or $env:OS -eq "Windows_NT") {
    $ClieBinary = Join-Path $ClieBinaryPath "clie-windows-amd64.exe"
} elseif ($IsMacOS) {
    # Check architecture for macOS
    $arch = uname -m
    if ($arch -eq "arm64") {
        $ClieBinary = Join-Path $ClieBinaryPath "clie-darwin-arm64"
    } else {
        $ClieBinary = Join-Path $ClieBinaryPath "clie-darwin-amd64"
    }
} else {
    # Linux - check architecture
    $arch = uname -m
    if ($arch -eq "aarch64" -or $arch -eq "arm64") {
        $ClieBinary = Join-Path $ClieBinaryPath "clie-linux-arm64"
    } else {
        $ClieBinary = Join-Path $ClieBinaryPath "clie-linux-amd64"
    }
}

if (Test-Path $ClieBinary) {
    # Create a function that invokes the binary (more reliable than Set-Alias for exe files)
    $funcDef = @"
function global:clie {
    & "$ClieBinary" `$args
}
function global:eac {
    & "$ClieBinary" run eac `$args
}
"@
    Invoke-Expression $funcDef
    Write-Host "✅ clie alias created -> $ClieBinary <args>" -ForegroundColor Green
    Write-Host "✅ eac alias created -> clie eac <args>" -ForegroundColor Green
} else {
    Write-Host "⚠️  clie binary not found at: $ClieBinary" -ForegroundColor Yellow
    Write-Host "   Run 'build clie' or 'go run ./go/cli/eac build clie' to build it" -ForegroundColor Gray
}

# Create top-level command aliases unless -NoAlias specified
if (-not $NoAlias) {
    New-TopLevelAliases
} else {
    Write-Host ""
    Write-Host "You can now use:" -ForegroundColor Cyan
    Write-Host "  Invoke-GoSrcCommand <command-name> [args...]" -ForegroundColor White
    Write-Host ""
    Write-Host "To create command aliases, call:" -ForegroundColor Cyan
    Write-Host "  New-TopLevelAliases" -ForegroundColor Gray
    Write-Host ""
}
