package init

import (
	"fmt"
	"os"
	"strings"

	claude "github.com/ready-to-release/eac/go/adapters/claude"
	gemini "github.com/ready-to-release/eac/go/adapters/gemini"
	openai "github.com/ready-to-release/eac/go/adapters/openai"
	"github.com/ready-to-release/eac/go/core/paths"
)

// agentConfig holds configuration for an AI provider.
type agentConfig struct {
	providerName string // "claude-api", "claude-cli", "openai", "gemini"
	envVarName   string // "ANTHROPIC_API_KEY", etc. (empty for claude-cli)
	model        string // "claude-3-haiku-20240307", etc.
	endpoint     string // API endpoint URL (empty for claude-cli)
}

// tokenConfig holds actual token values (for personal config).
type tokenConfig struct {
	aiToken  string // Actual AI API token
	gitToken string // Actual Git API token
}

// configureAgent configures the AI provider based on user input.
func configureAgent(aiProvider string) (*agentConfig, error) {
	config := &agentConfig{}

	// Configure provider based on --ai flag
	if err := configureProvider(config, aiProvider); err != nil {
		return nil, err
	}

	displayProviderInfo(config)
	return config, nil
}

// configureProvider sets up the config based on the provider key.
func configureProvider(config *agentConfig, provider string) error {
	switch strings.ToLower(provider) {
	case "claude-api":
		config.providerName = "claude-api"
		config.envVarName = "ANTHROPIC_API_KEY"
		config.model = claude.DefaultModel
		config.endpoint = "https://api.anthropic.com/v1"

	case "openai":
		config.providerName = "openai"
		config.envVarName = "OPENAI_API_KEY"
		config.model = openai.DefaultModel
		config.endpoint = "https://api.openai.com/v1"

	case "gemini":
		config.providerName = "gemini"
		config.envVarName = "GOOGLE_API_KEY"
		config.model = gemini.DefaultModel
		config.endpoint = "https://generativelanguage.googleapis.com"

	default:
		return fmt.Errorf("unsupported provider: %s\nSupported: claude-api, openai, gemini", provider)
	}

	return nil
}

// displayProviderInfo shows information about the selected provider.
func displayProviderInfo(config *agentConfig) {
	log.Info("")
	log.Info(fmt.Sprintf("✓ %s selected", config.providerName))
	if config.envVarName != "" {
		log.Info(fmt.Sprintf("  Environment variable: %s", config.envVarName))
	}

	// Provider-specific API key instructions
	switch config.providerName {
	case "claude-api":
		log.Info("  Get your API key at: https://claude.ai/settings/api")
		log.Info("  Note: Personal or workspace-owned API keys both work")
		log.Info("  Requires: ANTHROPIC_API_KEY environment variable")
	case "claude-cli":
		log.Info("  Uses Claude Code CLI (no API key needed)")
		log.Info("  Note: Requires Claude Code to be installed and authenticated")
	case "openai":
		log.Info("  Get your API key at: https://platform.openai.com/api-keys")
	case "gemini":
		log.Info("  Get your API key at: https://makersuite.google.com/app/apikey")
	}

	log.Info("")
	log.Info("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	log.Info("")
}

// writeConfig writes the EAC configuration (team or personal based on tokens).
func writeConfig(workspaceRoot string, config *agentConfig, tokens *tokenConfig) (string, error) {
	// Determine which file to write and whether to use env vars or direct tokens
	var configPath string
	var useEnvVars bool

	if tokens.aiToken != "" {
		// User provided AI token - write personal config with direct values
		configPath = paths.EACConfigPersonalFilePath(workspaceRoot)
		useEnvVars = false
		log.Info("📝 Creating personal configuration with actual tokens...")
	} else {
		// No tokens provided - write team config with env var placeholders
		configPath = paths.EACConfigFilePath(workspaceRoot)
		useEnvVars = true
		log.Info("📝 Creating team configuration with environment variable placeholders...")
	}

	// Build config content
	content := buildConfigContent(config, tokens, useEnvVars)

	// Write to file
	if err := os.WriteFile(configPath, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("failed to write config file: %w", err)
	}

	return configPath, nil
}

// buildConfigContent builds the YAML config content.
func buildConfigContent(config *agentConfig, tokens *tokenConfig, useEnvVars bool) string {
	var content strings.Builder

	// Header comment
	if useEnvVars {
		content.WriteString("# EAC Configuration (Team/Shared)\n")
		content.WriteString("# Generated by: eac init command\n")
		content.WriteString("# SAFE TO COMMIT: Contains environment variable placeholders\n")
		content.WriteString("#\n")
		content.WriteString("# This file is committed and shared across the team.\n")
		content.WriteString("# Used by eac CLI, CI/CD, and production workflows.\n")
		content.WriteString("#\n")
		content.WriteString("# For local development with Claude CLI (no API costs):\n")
		content.WriteString("# - Run: .\\importer.ps1\n")
		content.WriteString("# - This creates: .eac/ai-provider.personal.yml (gitignored)\n")
		content.WriteString("# - Personal config takes precedence over this team config\n")
	} else {
		content.WriteString("# EAC Configuration (Personal)\n")
		content.WriteString("# Generated by: eac init command\n")
		content.WriteString("# GITIGNORED: Contains actual token values\n")
		content.WriteString("# DO NOT COMMIT THIS FILE\n")
		content.WriteString("#\n")
		content.WriteString("# This file is specific to your machine and contains actual API tokens.\n")
		content.WriteString("# You can manually change tokens to ${ENV_VAR} format if preferred.\n")
	}
	content.WriteString("\n")

	// AI configuration
	content.WriteString("ai:\n")
	content.WriteString(fmt.Sprintf("  provider: %s\n", config.providerName))
	content.WriteString(fmt.Sprintf("  model: %s\n", config.model))

	if config.endpoint != "" {
		content.WriteString(fmt.Sprintf("  endpoint: %s\n", config.endpoint))
	}

	if config.envVarName != "" {
		if useEnvVars {
			content.WriteString(fmt.Sprintf("  api_key: ${%s}\n", config.envVarName))
		} else {
			content.WriteString(fmt.Sprintf("  api_key: %s\n", tokens.aiToken))
		}
	}

	// Git configuration
	content.WriteString("\ngit:\n")
	if useEnvVars {
		content.WriteString("  token: ${GIT_TOKEN}\n")
	} else if tokens.gitToken != "" {
		content.WriteString(fmt.Sprintf("  token: %s\n", tokens.gitToken))
	} else {
		content.WriteString("  token: \"\"\n")
	}

	return content.String()
}
