package init

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
)

// ConfigGenerator defines the interface for generating repository configuration.
type ConfigGenerator interface {
	// Generate creates a repository.yml configuration from scan results.
	// Returns the YAML content as a string or an error if generation fails.
	Generate(workspaceRoot string, scanResult *ScanResult) (string, error)
}

// RuleBasedGenerator generates configuration using predefined rules and heuristics.
type RuleBasedGenerator struct{}

// NewRuleBasedGenerator creates a new rule-based configuration generator.
func NewRuleBasedGenerator() *RuleBasedGenerator {
	return &RuleBasedGenerator{}
}

// Generate implements ConfigGenerator for rule-based generation.
func (g *RuleBasedGenerator) Generate(workspaceRoot string, scanResult *ScanResult) (string, error) {
	var buf strings.Builder

	repoName := filepath.Base(workspaceRoot)
	if repoName == "" || repoName == "." {
		repoName = "project"
	}

	buf.WriteString("# EAC Repository Configuration\n")
	buf.WriteString("# Auto-generated from repository scan\n")
	buf.WriteString("# Generated by: eac init --scan\n")
	buf.WriteString("\nrepository:\n")
	buf.WriteString(fmt.Sprintf("  name: %s\n", repoName))
	buf.WriteString("  description: Auto-detected multi-module repository\n")
	buf.WriteString("\nmodules:\n")

	for _, mod := range scanResult.Modules {
		buf.WriteString(fmt.Sprintf("  - moniker: %s\n", normalizeMoniker(mod.Name)))
		buf.WriteString(fmt.Sprintf("    description: %s\n", moduleDescription(mod)))
		buf.WriteString("    components:\n")
		buf.WriteString(fmt.Sprintf("      - type: %s\n", mod.Language))
		buf.WriteString(fmt.Sprintf("        root: %s\n", mod.Root))
		buf.WriteString("\n")
	}

	return buf.String(), nil
}

// normalizeMoniker converts a module name to a valid EAC moniker.
// Monikers must be lowercase, hyphen-separated, and contain only [a-z0-9-].
func normalizeMoniker(name string) string {
	s := strings.ToLower(name)

	// Strip scoped npm package prefix (@org/pkg → pkg)
	if strings.HasPrefix(s, "@") {
		if idx := strings.Index(s, "/"); idx >= 0 {
			s = s[idx+1:]
		} else {
			s = s[1:]
		}
	}

	// Replace separators with hyphens
	s = strings.ReplaceAll(s, "_", "-")
	s = strings.ReplaceAll(s, " ", "-")
	s = strings.ReplaceAll(s, "/", "-")

	// Strip characters outside [a-z0-9-]
	s = regexp.MustCompile(`[^a-z0-9-]`).ReplaceAllString(s, "")

	// Collapse multiple hyphens and trim
	s = regexp.MustCompile(`-+`).ReplaceAllString(s, "-")
	return strings.Trim(s, "-")
}

// moduleDescription returns a descriptive string for a module based on its name and root.
func moduleDescription(mod ModuleInfo) string {
	if mod.Root == "." || mod.Root == "" {
		return fmt.Sprintf("Root %s module", mod.Language)
	}
	moniker := normalizeMoniker(mod.Name)
	return fmt.Sprintf("%s %s module at %s", moniker, mod.Language, mod.Root)
}

// AIGenerator generates configuration using AI-powered analysis.
type AIGenerator struct {
	provider string
	deps     *Deps
}

// NewAIGenerator creates a new AI-powered configuration generator.
func NewAIGenerator(provider string) *AIGenerator {
	return &AIGenerator{
		provider: provider,
		deps:     defaultDeps(),
	}
}

// newAIGenerator creates a new AI-powered configuration generator with injectable dependencies.
func newAIGenerator(provider string, deps *Deps) *AIGenerator {
	return &AIGenerator{
		provider: provider,
		deps:     deps,
	}
}

// Generate implements ConfigGenerator for AI-based generation.
func (g *AIGenerator) Generate(workspaceRoot string, scanResult *ScanResult) (string, error) {
	return generateConfig(g.deps, workspaceRoot, scanResult, g.provider)
}

// GenerateWithFallback attempts to generate config with the primary generator,
// falling back to the fallback generator if the primary fails.
func GenerateWithFallback(workspaceRoot string, scanResult *ScanResult, primary, fallback ConfigGenerator) (string, error) {
	result, err := primary.Generate(workspaceRoot, scanResult)
	if err != nil {
		return fallback.Generate(workspaceRoot, scanResult)
	}
	return result, nil
}
