package init

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/ready-to-release/eac/go/core/config"
)

// generateRepositoryYML generates a minimal repository.yml skeleton.
// It writes only the repository name and an empty modules list — no system
// defaults are ever serialized to disk.
func generateRepositoryYML(workspaceRoot, eacDir string) error {
	repoName := filepath.Base(workspaceRoot)

	content := `# EAC Repository Configuration
# Generated by: eac init
#
# This file defines your repository settings and module domain.
# Edit this file to customize modules, dependencies, and build settings.
#
# Documentation: https://ready-to-release.github.io/eac/

repository:
  name: ` + repoName + `

modules: []
`

	path := filepath.Join(eacDir, "repository.yml")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("failed to write repository.yml: %w", err)
	}

	log.Info("   ✓ Generated repository.yml")
	return nil
}

// generateBooksYML generates books.yml with empty template.
func generateBooksYML(eacDir string) error {
	content := `# Documentation Books Configuration
# Generated by: eac init
#
# Define documentation books for your project.
# Each book represents a documentation site built with MkDocs.
#
# Example:
#   books:
#     - name: docs
#       title: Project Documentation
#       description: Main documentation site
#       output: site
#       sources:
#         - path: docs
#
# Documentation: https://ready-to-release.github.io/eac/

books: []
`

	path := filepath.Join(eacDir, "books.yml")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("failed to write books.yml: %w", err)
	}

	log.Info("   ✓ Generated books.yml")
	return nil
}

// generateEnvironmentsYML generates environments.yml with empty template.
func generateEnvironmentsYML(eacDir string) error {
	content := `# Test Environments Configuration
# Generated by: eac init
#
# Define test environments for your project.
# Environments specify where and how tests run.
#
# Example:
#   environments:
#     - moniker: local
#       name: Local Development
#       description: Local development environment
#       level: L0
#
#     - moniker: staging
#       name: Staging
#       description: Pre-production staging environment
#       level: L2
#
# Test Levels:
#   L0 - Unit tests (no external dependencies)
#   L1 - Integration tests (local dependencies)
#   L2 - System tests (staging environment)
#   L3 - Acceptance tests (production-like)
#   L4 - Production validation
#
# Documentation: https://ready-to-release.github.io/eac/

environments: []
`

	path := filepath.Join(eacDir, "environments.yml")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("failed to write environments.yml: %w", err)
	}

	log.Info("   ✓ Generated environments.yml")
	return nil
}

// generateRepoConfigFromScan generates repository YAML from scan results using the
// strategy pattern: AI generation with rule-based fallback, or rule-based only.
// This is the shared logic used by both first-time init and re-initialization.
//
// Generators are resolved from deps if injected (for testing), otherwise constructed
// from aiProvider at runtime.
func generateRepoConfigFromScan(deps *Deps, workspaceRoot, aiProvider string, scanResult *ScanResult) (string, error) {
	fallback := deps.FallbackGenerator
	if fallback == nil {
		fallback = NewRuleBasedGenerator()
	}

	if aiProvider != "" {
		log.Info(fmt.Sprintf("🤖 Generating configuration with AI (%s)...", aiProvider))
		primary := deps.PrimaryGenerator
		if primary == nil {
			primary = newAIGenerator(aiProvider, deps)
		}
		repoYAML, err := GenerateWithFallback(workspaceRoot, scanResult, primary, fallback)
		if err != nil {
			return "", fmt.Errorf("failed to generate configuration: %w", err)
		}
		log.Info("   ✓ Configuration generated")
		return repoYAML, nil
	}

	log.Info("🔧 Generating configuration (rule-based)...")
	repoYAML, err := fallback.Generate(workspaceRoot, scanResult)
	if err != nil {
		return "", fmt.Errorf("failed to generate configuration: %w", err)
	}
	log.Info("   ✓ Configuration generated")
	return repoYAML, nil
}

// validateGeneratedYAML checks that a generated YAML string can be parsed as a
// RepositoryConfig, invoking all custom unmarshalers (including the list-format
// check on ModuleComponents). Returns an error if the YAML is invalid.
func validateGeneratedYAML(repoYAML string) error {
	var cfg config.RepositoryConfig
	if err := yaml.Unmarshal([]byte(repoYAML), &cfg); err != nil {
		return fmt.Errorf("generated config is not valid: %w", err)
	}
	return nil
}

// generateWithScan scans the repository and generates configuration files.
func generateWithScan(deps *Deps, workspaceRoot, eacDir, aiProvider string) error {
	log.Info("")
	log.Info("🔍 Scanning repository structure...")

	// Run scanner
	scanResult, err := ScanRepository(workspaceRoot)
	if err != nil {
		return fmt.Errorf("failed to scan repository: %w", err)
	}

	// Report scan results
	if len(scanResult.Modules) == 0 {
		log.Warn("   ⚠️  No modules detected")
		log.Info("   Falling back to manual configuration")

		// Generate empty templates
		if err := generateBooksYML(eacDir); err != nil {
			return err
		}
		if err := generateEnvironmentsYML(eacDir); err != nil {
			return err
		}
		return nil
	}

	log.Info(fmt.Sprintf("   ✓ Detected: %d module(s)", len(scanResult.Modules)))
	for _, mod := range scanResult.Modules {
		log.Info(fmt.Sprintf("      - %s (%s) at %s", mod.Name, mod.Language, mod.Root))
	}

	// Generate repository.yml using shared strategy logic
	log.Info("")
	repoYAML, err := generateRepoConfigFromScan(deps, workspaceRoot, aiProvider, scanResult)
	if err != nil {
		return err
	}

	if aiProvider == "" {
		log.Info("")
		log.Info("   💡 Tip: Use --ai-provider claude-api for enhanced descriptions")
	}

	// Validate before writing — prevents corrupt .eac/repository.yml from reaching disk.
	// If AI generation produced invalid YAML, fall back to rule-based and validate again.
	if err := validateGeneratedYAML(repoYAML); err != nil {
		log.Warn(fmt.Sprintf("   ⚠️  Generated config failed validation (%v), regenerating with rule-based", err))
		ruleGen := NewRuleBasedGenerator()
		repoYAML, err = ruleGen.Generate(workspaceRoot, scanResult)
		if err != nil {
			return fmt.Errorf("rule-based fallback failed: %w", err)
		}
		if err := validateGeneratedYAML(repoYAML); err != nil {
			return fmt.Errorf("rule-based config is also invalid: %w", err)
		}
	}

	// Write repository.yml
	repoPath := filepath.Join(eacDir, "repository.yml")
	if err := os.WriteFile(repoPath, []byte(repoYAML), 0o644); err != nil {
		return fmt.Errorf("failed to write repository.yml: %w", err)
	}
	log.Info(fmt.Sprintf("   ✓ Generated %s", repoPath))

	// Generate other config files
	if err := generateBooksYML(eacDir); err != nil {
		return err
	}
	if err := generateEnvironmentsYML(eacDir); err != nil {
		return err
	}
	return nil
}
