title: Continuous Delivery
nav:
  - ra-stage-breakdown.md
  - cde-stage-breakdown.md
  - deployment-strategies.md
  - precommit-quality-gates.md
  - merge-request-quality-gates.md
  - release-quality-thresholds.md
  - repository-comparison.md
  - environment-types.md
  - network-zones.md
  - verification-types.md
  - deployment-rings.md
  - release-documentation.md
