#Requires -Version 5.1
<#
.SYNOPSIS
    Initialize local r2r configuration for EAC development

.DESCRIPTION
    Creates .r2r/r2r-cli.local.yml configuration file for local Docker development.
    Configures r2r to use locally built Docker images instead of pulling from registry.

.PARAMETER ImageTag
    Docker image tag to use. Default is 'ext-eac:dev'.

.PARAMETER Force
    Overwrite existing configuration file.

.PARAMETER MountWorkspace
    Add volume mount for live workspace development.

.PARAMETER Debug
    Add debug environment variables.

.EXAMPLE
    # Basic initialization
    .\init-local.ps1

.EXAMPLE
    # With custom image tag
    .\init-local.ps1 -ImageTag "ext-eac:my-feature"

.EXAMPLE
    # Force overwrite existing config
    .\init-local.ps1 -Force

.EXAMPLE
    # With workspace mount and debug
    .\init-local.ps1 -MountWorkspace -EnableDebug
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false)]
    [string]$ImageTag = "ext-eac:dev",

    [Parameter(Mandatory=$false)]
    [switch]$Force,

    [Parameter(Mandatory=$false)]
    [switch]$MountWorkspace,

    [Parameter(Mandatory=$false)]
    [switch]$EnableDebug
)

$ErrorActionPreference = "Stop"

function Write-ColorOutput {
    param(
        [string]$Message,
        [string]$Color = "White"
    )
    Write-Host $Message -ForegroundColor $Color
}

function Get-RepositoryRoot {
    try {
        $root = git rev-parse --show-toplevel 2>&1
        if ($LASTEXITCODE -ne 0) {
            return $null
        }
        # Convert to Windows path if needed
        if ($root -match "^/[a-z]/") {
            $root = $root -replace "^/([a-z])/", '$1:/'
            $root = $root -replace "/", "\"
        }
        return $root
    }
    catch {
        return $null
    }
}

function Add-ToGitignore {
    param(
        [string]$RepoRoot,
        [string]$Pattern
    )

    $gitignorePath = Join-Path $RepoRoot ".gitignore"

    if (Test-Path $gitignorePath) {
        $content = Get-Content $gitignorePath -Raw
        if ($content -notmatch [regex]::Escape($Pattern)) {
            Add-Content -Path $gitignorePath -Value "`n# Local r2r development configuration"
            Add-Content -Path $gitignorePath -Value $Pattern
            Write-ColorOutput "  ✓ Added to .gitignore" "Green"
        }
        else {
            Write-ColorOutput "  ✓ Already in .gitignore" "Green"
        }
    }
    else {
        Set-Content -Path $gitignorePath -Value "# Local r2r development configuration"
        Add-Content -Path $gitignorePath -Value $Pattern
        Write-ColorOutput "  ✓ Created .gitignore" "Green"
    }
}

# Main script
Write-ColorOutput "R2R Local Development Configuration" "Cyan"
Write-ColorOutput ""

# Find repository root
$repoRoot = Get-RepositoryRoot
if (-not $repoRoot) {
    Write-ColorOutput "Error: Not in a git repository" "Red"
    Write-ColorOutput "Please run this script from within a git repository" "Yellow"
    Write-ColorOutput ""
    Write-ColorOutput "If you want to initialize a new repository:" "Yellow"
    Write-ColorOutput "  git init" "Gray"
    exit 1
}

Write-ColorOutput "Repository: $repoRoot" "White"

# Create .r2r directory
$r2rDir = Join-Path $repoRoot ".r2r"
if (-not (Test-Path $r2rDir)) {
    New-Item -ItemType Directory -Path $r2rDir -Force | Out-Null
    Write-ColorOutput "✓ Created .r2r directory" "Green"
}
else {
    Write-ColorOutput "✓ .r2r directory exists" "Green"
}

# Check if config already exists
$configPath = Join-Path $r2rDir "r2r-cli.local.yml"
if ((Test-Path $configPath) -and -not $Force) {
    Write-ColorOutput ""
    Write-ColorOutput "Configuration file already exists:" "Yellow"
    Write-ColorOutput "  $configPath" "White"
    Write-ColorOutput ""
    Write-ColorOutput "Use -Force to overwrite" "Yellow"
    exit 1
}

Write-ColorOutput ""
Write-ColorOutput "Creating local configuration..." "Cyan"

# Build configuration content
$config = @"
# Local R2R Development Configuration
# Generated by: init-local.ps1
# This file is gitignored and should not be committed
#
# This configuration tells r2r to use locally built Docker images
# instead of pulling from the registry.

# Global flag to prefer local images
load_local: true

extensions:
  - name: 'eac'
    image: '$ImageTag'
    load_local: true
    image_pull_policy: 'Never'
    auto_remove_children: false
"@

# Add debug environment variables if requested
if ($EnableDebug) {
    $config += @"


    # Debug environment variables
    env:
      - name: 'EAC_DEBUG'
        value: 'true'
      - name: 'R2R_LOCAL_DEV'
        value: 'true'
"@
}

# Add workspace mount if requested
if ($MountWorkspace) {
    $config += @"


    # Volume mounts for live development
    volumes:
      - host: '.'
        container: '/workspace'
        readonly: false
      - host: '.git'
        container: '/.git'
        readonly: true
"@
}

# Write configuration file
try {
    Set-Content -Path $configPath -Value $config -Encoding UTF8
    Write-ColorOutput "✓ Configuration created: $configPath" "Green"
}
catch {
    Write-ColorOutput "Error: Failed to write configuration file" "Red"
    Write-ColorOutput $_.Exception.Message "Red"
    exit 1
}

# Add to .gitignore
Write-ColorOutput ""
Write-ColorOutput "Updating .gitignore..." "Cyan"
Add-ToGitignore -RepoRoot $repoRoot -Pattern ".r2r/*.local.yml"

Write-ColorOutput ""
Write-ColorOutput "✅ Local development configuration complete!" "Green"
Write-ColorOutput ""
Write-ColorOutput "Configuration Details:" "Cyan"
Write-ColorOutput "  File: $configPath" "White"
Write-ColorOutput "  Image: $ImageTag" "White"
Write-ColorOutput "  Mode: Local Docker (no remote pulls)" "White"
if ($EnableDebug) {
    Write-ColorOutput "  Debug: Enabled" "White"
}
if ($MountWorkspace) {
    Write-ColorOutput "  Workspace Mount: Enabled" "White"
}

Write-ColorOutput ""
Write-ColorOutput "Next Steps:" "Cyan"
Write-ColorOutput "  1. Ensure Docker image is built:" "White"
Write-ColorOutput "     .\scripts\pwsh\local-dev\build-local.ps1" "Gray"
Write-ColorOutput ""
Write-ColorOutput "  2. Set repository root environment variable:" "White"
Write-ColorOutput "     `$env:R2R_REPO_ROOT = `"$repoRoot`"" "Gray"
Write-ColorOutput ""
Write-ColorOutput "  3. Test r2r with local image:" "White"
Write-ColorOutput "     r2r eac help" "Gray"
Write-ColorOutput ""
