title: Command Areas
nav:
  - index.md
  - Books:
    - books-overview.md
    - books-configuration.md
    - books-commands.md
  - Build:
    - build-overview.md
    - build-configuration.md
    - build-commands.md
  - Design:
    - design-overview.md
    - design-configuration.md
    - design-commands.md
  - Pipeline:
    - pipeline-overview.md
    - pipeline-configuration.md
    - pipeline-commands.md
    - pipeline-ci-commands.md
  - Release:
    - release-overview.md
    - release-configuration.md
    - release-commands.md
  - Risk Management:
    - risks-overview.md
    - risks-configuration.md
    - risks-commands.md
  - Security:
    - security-overview.md
    - security-configuration.md
    - security-commands.md
  - Specifications:
    - specifications-overview.md
    - specifications-configuration.md
    - specifications-commands.md
  - Templates:
    - templates-overview.md
    - templates-configuration.md
    - templates-commands.md
  - Test:
    - test-overview.md
    - test-configuration.md
    - test-commands.md
  - Validate:
    - validate-overview.md
    - validate-configuration.md
    - validate-commands.md
  - Workspace:
    - workspace-overview.md
    - workspace-configuration.md
    - workspace-commands.md
