title: show
nav:
  - index.md
  - show.md
  - approval-comments.md
  - approve-summary.md
  - artifacts.md
  - books.md
  - build-summary.md
  - build-times.md
  - changelog.md
  - ci-summary.md
  - component-types.md
  - config.md
  - dependencies.md
  - dependency-ci-summary.md
  - deps-setup-summary.md
  - environments.md
  - files.md
  - files-changed.md
  - files-staged.md
  - help.md
  - lint-summary.md
  - modules.md
  - release-notes.md
  - release-summary.md
  - scan-summary.md
  - specs.md
  - suite.md
  - test-results.md
  - test-summary.md
  - test-timings.md
  - tests.md
  - trigger-summary.md
  - valid-commands.md
  - workspaces.md
