title: get
nav:
  - index.md
  - get.md
  - artifacts.md
  - build-deps.md
  - build-times.md
  - changed-modules.md
  - changed-modules-ci.md
  - commands.md
  - config.md
  - dependencies.md
  - environments.md
  - execution-order.md
  - files.md
  - modules.md
  - specs-unused-steps.md
  - suite.md
  - test-timings.md
  - tests.md
  - valid-commands.md
