title: Modules
nav:
  - index.md
  - eac-cli.md
  - core.md
  - eac-mcp-server.md
  - ext-eac.md
  - repository.md
  - docs.md
  - templates.md
  - r2r-installer.md
  - vscode-commit.md
  - implicit-cli.md
