title: Commands
nav:
  - index.md
  - build/
  - create/
  - deploy.md
  - drawio/
  - extension-meta.md
  - get/
  - help/
  - init/
  - lint.md
  - pipeline/
  - release/
  - scan/
  - serve/
  - show/
  - templates/
  - test/
  - update/
  - validate/
  - work/
