title: drawio
nav:
  - index.md
  - "drawio": drawio.md
  - "drawio create": create.md
  - "drawio decode": decode.md
  - "drawio embed": embed.md
  - "drawio encode": encode.md
  - "drawio info": info.md
  - "drawio render": render.md
