title: release
nav:
  - index.md
  - release.md
  - this.md
  - changelog.md
  - check-ci.md
  - get-version.md
  - pending.md
  - tag-pending.md
  - generate-module-calver.md
  - r2r-cli.md
  - validate-release.md
  - validate-release-version.md
