title: release
nav:
  - index.md
  - "release": release.md
  - "release this": this.md
  - "release await-deps": await-deps.md
  - "release changelog": changelog.md
  - "release check-ci": check-ci.md
  - "release check-exists": check-exists.md
  - "release check-pending": check-pending.md
  - "release cleanup": cleanup.md
  - "release execute-layers": execute-layers.md
  - "release eac-ext": eac-ext.md
  - "release extract-version": extract-version.md
  - "release get-module-calver": get-module-calver.md
  - "release get-version": get-version.md
  - "release pending": pending.md
  - "release prune": prune.md
  - "release prune-packages": prune-packages.md
  - "release clie": clie.md
  - "release tag-pending": tag-pending.md
