package github

import (
	"context"
	"errors"
	"strings"
	"testing"
	"time"
)

func TestNewCLIMock(t *testing.T) {
	mock := NewCLIMock()
	if mock == nil {
		t.Fatal("expected non-nil mock")
	}

	if mock.responses == nil {
		t.Error("expected responses map to be initialized")
	}

	if mock.errors == nil {
		t.Error("expected errors map to be initialized")
	}

	if mock.calls == nil {
		t.Error("expected calls slice to be initialized")
	}
}

func TestCLIMock_WithWorkflowRuns(t *testing.T) {
	runs := []WorkflowRun{
		{
			ID:         123456789,
			HeadSHA:    "abc123",
			Status:     "completed",
			Conclusion: "success",
			CreatedAt:  time.Now(),
			Name:       "CI",
		},
		{
			ID:         987654321,
			HeadSHA:    "def456",
			Status:     "in_progress",
			Conclusion: "",
			CreatedAt:  time.Now(),
			Name:       "CI",
		},
	}

	mock := NewCLIMock().WithWorkflowRuns("ci.yml", runs)

	// Execute the command that would be generated by GHClient
	output, err := mock.Exec("run", "list", "-w", "ci.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Verify the output contains expected data
	outputStr := string(output)
	if !strings.Contains(outputStr, "abc123") {
		t.Error("expected output to contain 'abc123'")
	}
	if !strings.Contains(outputStr, "123456789") {
		t.Error("expected output to contain run ID 123456789")
	}
	if !strings.Contains(outputStr, "in_progress") {
		t.Error("expected output to contain 'in_progress'")
	}
}

func TestCLIMock_WithWorkflowRuns_MultipleWorkflows(t *testing.T) {
	mock := NewCLIMock().
		WithWorkflowRuns("ci.yml", []WorkflowRun{
			{ID: 111, HeadSHA: "sha1", Status: "completed", Conclusion: "success"},
		}).
		WithWorkflowRuns("release.yml", []WorkflowRun{
			{ID: 222, HeadSHA: "sha2", Status: "completed", Conclusion: "success"},
		})

	// CI workflow
	output, err := mock.Exec("run", "list", "-w", "ci.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(string(output), "sha1") {
		t.Error("expected ci.yml output to contain sha1")
	}
	if strings.Contains(string(output), "sha2") {
		t.Error("expected ci.yml output to NOT contain sha2")
	}

	// Release workflow
	output, err = mock.Exec("run", "list", "-w", "release.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(string(output), "sha2") {
		t.Error("expected release.yml output to contain sha2")
	}
	if strings.Contains(string(output), "sha1") {
		t.Error("expected release.yml output to NOT contain sha1")
	}
}

func TestCLIMock_WithRelease(t *testing.T) {
	mock := NewCLIMock().WithRelease("v1.0.0", "Release v1.0.0")

	// Test release list
	output, err := mock.Exec("release", "list", "--limit", "100", "--json", "tagName,name,isDraft")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	outputStr := string(output)
	if !strings.Contains(outputStr, "v1.0.0") {
		t.Error("expected output to contain 'v1.0.0'")
	}
	if !strings.Contains(outputStr, "Release v1.0.0") {
		t.Error("expected output to contain 'Release v1.0.0'")
	}
}

func TestCLIMock_WithRelease_Multiple(t *testing.T) {
	mock := NewCLIMock().
		WithRelease("v1.0.0", "Release v1.0.0").
		WithRelease("v1.1.0", "Release v1.1.0").
		WithRelease("v1.2.0", "Release v1.2.0")

	output, err := mock.Exec("release", "list", "--limit", "100", "--json", "tagName,name,isDraft")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	outputStr := string(output)
	if !strings.Contains(outputStr, "v1.0.0") {
		t.Error("expected output to contain 'v1.0.0'")
	}
	if !strings.Contains(outputStr, "v1.1.0") {
		t.Error("expected output to contain 'v1.1.0'")
	}
	if !strings.Contains(outputStr, "v1.2.0") {
		t.Error("expected output to contain 'v1.2.0'")
	}
}

func TestCLIMock_WithError(t *testing.T) {
	testErr := errors.New("workflow not found")
	mock := NewCLIMock().WithError("run list -w missing.yml", testErr)

	_, err := mock.Exec("run", "list", "-w", "missing.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name")
	if err == nil {
		t.Fatal("expected error, got nil")
	}

	if !errors.Is(err, testErr) {
		t.Errorf("expected error to be %v, got %v", testErr, err)
	}
}

func TestCLIMock_WithError_PartialCommand(t *testing.T) {
	testErr := errors.New("release not found")
	mock := NewCLIMock().WithError("release view v99.0.0", testErr)

	// Should match even with --json flag
	_, err := mock.Exec("release", "view", "v99.0.0", "--json", "tagName")
	if err == nil {
		t.Fatal("expected error, got nil")
	}

	if !errors.Is(err, testErr) {
		t.Errorf("expected error to be %v, got %v", testErr, err)
	}
}

func TestCLIMock_CallTracking(t *testing.T) {
	mock := NewCLIMock().WithWorkflowRuns("ci.yml", []WorkflowRun{
		{ID: 123, HeadSHA: "abc", Status: "completed", Conclusion: "success"},
	})

	// Make several calls
	mock.Exec("run", "list", "-w", "ci.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name")
	mock.Exec("run", "list", "-w", "ci.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name")
	mock.Exec("release", "list", "--limit", "100", "--json", "tagName,name,isDraft")

	if len(mock.calls) != 3 {
		t.Errorf("expected 3 calls, got %d", len(mock.calls))
	}

	// Verify first call
	if mock.calls[0].Command != "run list" {
		t.Errorf("expected first command to be 'run list', got '%s'", mock.calls[0].Command)
	}

	// Verify last call
	if mock.calls[2].Command != "release list" {
		t.Errorf("expected last command to be 'release list', got '%s'", mock.calls[2].Command)
	}

	// Verify args
	if len(mock.calls[0].Args) < 3 {
		t.Error("expected args to be captured")
	}
}

func TestCLIMock_GetCalls(t *testing.T) {
	mock := NewCLIMock().WithWorkflowRuns("ci.yml", []WorkflowRun{})

	mock.Exec("run", "list", "-w", "ci.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name")

	calls := mock.GetCalls()
	if len(calls) != 1 {
		t.Errorf("expected 1 call, got %d", len(calls))
	}
}

func TestCLIMock_ResetCalls(t *testing.T) {
	mock := NewCLIMock().WithWorkflowRuns("ci.yml", []WorkflowRun{})

	mock.Exec("run", "list", "-w", "ci.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name")
	mock.ResetCalls()

	if len(mock.calls) != 0 {
		t.Errorf("expected 0 calls after reset, got %d", len(mock.calls))
	}
}

func TestCLIMock_ExecContext(t *testing.T) {
	mock := NewCLIMock().WithWorkflowRuns("ci.yml", []WorkflowRun{
		{ID: 123, HeadSHA: "abc", Status: "completed", Conclusion: "success"},
	})

	ctx := context.Background()
	output, err := mock.ExecContext(ctx, "run", "list", "-w", "ci.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(string(output), "abc") {
		t.Error("expected output to contain 'abc'")
	}
}

func TestCLIMock_ExecContext_Canceled(t *testing.T) {
	mock := NewCLIMock().WithWorkflowRuns("ci.yml", []WorkflowRun{})

	ctx, cancel := context.WithCancel(context.Background())
	cancel() // Cancel immediately

	_, err := mock.ExecContext(ctx, "run", "list", "-w", "ci.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name")
	if err == nil {
		t.Fatal("expected error with canceled context")
	}

	if !errors.Is(err, context.Canceled) {
		t.Errorf("expected context.Canceled error, got %v", err)
	}
}

func TestCLIMock_ReleaseView(t *testing.T) {
	mock := NewCLIMock().WithRelease("v1.0.0", "Release v1.0.0")

	// Test release view (specific tag)
	output, err := mock.Exec("release", "view", "v1.0.0", "--json", "tagName")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	outputStr := string(output)
	if !strings.Contains(outputStr, "v1.0.0") {
		t.Error("expected output to contain 'v1.0.0'")
	}
}

func TestCLIMock_ReleaseView_NotFound(t *testing.T) {
	mock := NewCLIMock() // No releases configured

	_, err := mock.Exec("release", "view", "v99.0.0", "--json", "tagName")
	if err == nil {
		t.Fatal("expected error for non-existent release")
	}
}

func TestCLIMock_RunView(t *testing.T) {
	mock := NewCLIMock().WithWorkflowRun(WorkflowRun{
		ID:         123456789,
		HeadSHA:    "abc123",
		Status:     "completed",
		Conclusion: "success",
		Name:       "CI",
	})

	output, err := mock.Exec("run", "view", "123456789", "--json", "databaseId,headSha,status,conclusion,name")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	outputStr := string(output)
	if !strings.Contains(outputStr, "123456789") {
		t.Error("expected output to contain run ID")
	}
	if !strings.Contains(outputStr, "abc123") {
		t.Error("expected output to contain SHA")
	}
}

func TestCLIMock_RunView_NotFound(t *testing.T) {
	mock := NewCLIMock() // No runs configured

	_, err := mock.Exec("run", "view", "999999", "--json", "databaseId,headSha,status,conclusion,name")
	if err == nil {
		t.Fatal("expected error for non-existent run")
	}
}

func TestCLIMock_WorkflowView(t *testing.T) {
	mock := NewCLIMock().WithWorkflow("ci.yml", "CI Workflow")

	output, err := mock.Exec("workflow", "view", "ci.yml", "--json", "name")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	outputStr := string(output)
	if !strings.Contains(outputStr, "CI Workflow") {
		t.Error("expected output to contain workflow name")
	}
}

func TestCLIMock_APICommand(t *testing.T) {
	treeFiles := []string{
		"go/main.go",
		"README.md",
		"docs/index.md",
	}

	mock := NewCLIMock().WithTreeFiles("abc123", treeFiles)

	output, err := mock.Exec("api", "repos/{owner}/{repo}/git/trees/abc123", "-q", ".tree[] | select(.type==\"blob\") | .path", "--paginate")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	outputStr := string(output)
	for _, file := range treeFiles {
		if !strings.Contains(outputStr, file) {
			t.Errorf("expected output to contain %s", file)
		}
	}
}

func TestCLIMock_CommandNormalization(t *testing.T) {
	// Test that command matching works with various flag combinations
	mock := NewCLIMock().WithWorkflowRuns("ci.yml", []WorkflowRun{
		{ID: 123, HeadSHA: "abc", Status: "completed", Conclusion: "success"},
	})

	// These should all match the same command
	testCases := [][]string{
		{"run", "list", "-w", "ci.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name"},
		{"run", "list", "-w", "ci.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name", "-L", "10"},
		{"run", "list", "-w", "ci.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name", "-s", "success"},
	}

	for i, args := range testCases {
		output, err := mock.Exec(args...)
		if err != nil {
			t.Errorf("test case %d: unexpected error: %v", i, err)
		}
		if !strings.Contains(string(output), "abc") {
			t.Errorf("test case %d: expected output to contain 'abc'", i)
		}
	}
}

func TestCLIMock_EmptyResponse(t *testing.T) {
	// Test commands that should return empty arrays
	mock := NewCLIMock()

	// Empty workflow runs
	output, err := mock.Exec("run", "list", "-w", "ci.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if string(output) != "[]" {
		t.Errorf("expected empty array, got %s", string(output))
	}

	// Empty releases
	output, err = mock.Exec("release", "list", "--limit", "100", "--json", "tagName,name,isDraft")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if string(output) != "[]" {
		t.Errorf("expected empty array, got %s", string(output))
	}
}

func TestCLIMock_LoadWorkflowRunsFixture(t *testing.T) {
	mock := NewCLIMock()

	err := mock.LoadWorkflowRunsFixture("ci.yml", "workflow_runs.json")
	if err != nil {
		t.Fatalf("unexpected error loading fixture: %v", err)
	}

	// Verify runs were loaded
	output, err := mock.Exec("run", "list", "-w", "ci.yml", "--json", "databaseId,headSha,status,conclusion,createdAt,name")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	outputStr := string(output)
	if !strings.Contains(outputStr, "abc123def456") {
		t.Error("expected fixture data to be loaded")
	}
	if !strings.Contains(outputStr, "123456789") {
		t.Error("expected fixture run ID to be loaded")
	}
}

func TestCLIMock_LoadReleasesFixture(t *testing.T) {
	mock := NewCLIMock()

	err := mock.LoadReleasesFixture("releases.json")
	if err != nil {
		t.Fatalf("unexpected error loading fixture: %v", err)
	}

	// Verify releases were loaded
	output, err := mock.Exec("release", "list", "--limit", "100", "--json", "tagName,name,isDraft")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	outputStr := string(output)
	if !strings.Contains(outputStr, "v1.0.0") {
		t.Error("expected fixture release to be loaded")
	}
	if !strings.Contains(outputStr, "v1.1.0") {
		t.Error("expected fixture release to be loaded")
	}
}

func TestCLIMock_LoadFixture_FileNotFound(t *testing.T) {
	mock := NewCLIMock()

	err := mock.LoadWorkflowRunsFixture("ci.yml", "nonexistent.json")
	if err == nil {
		t.Fatal("expected error for missing fixture file")
	}
}
