title: Release Management
nav:
  - index.md
  - understanding-release-folder.md
  - release-workflow-variants.md
  - prepare-module-release.md
  - generate-changelog.md
  - create-release-tag.md
  - check-ci-before-release.md
  - view-changelog-release-notes.md
  - view-approval-comments.md
  - view-specifications.md
