title: Categories
nav:
  - index.md
  - build.md
  - create.md
  - get.md
  - help.md
  - init.md
  - pipeline.md
  - release.md
  - scan.md
  - serve.md
  - show.md
  - templates.md
  - test.md
  - update.md
  - validate.md
  - work.md
