title: validate
nav:
  - index.md
  - "validate": validate.md
  - "validate artifacts": artifacts.md
  - "validate books": books.md
  - "validate config": config.md
  - "validate contracts": contracts.md
  - "validate control-tags": control-tags.md
  - "validate dependabot": dependabot.md
  - "validate dependencies": dependencies.md
  - "validate design": design.md
  - "validate docs": docs.md
  - "validate go-tidy": go-tidy.md
  - "validate markdown": markdown.md
  - "validate module-files": module-files.md
  - "validate module-hierarchy": module-hierarchy.md
  - "validate release": release.md
  - "validate release-version": release-version.md
  - "validate risk-catalog": risk-catalog.md
  - "validate risk-profile": risk-profile.md
  - "validate specs": specs.md
  - "validate test-tags": test-tags.md
  - "validate version": version.md
