title: validate
nav:
  - index.md
  - validate.md
  - artifacts.md
  - books.md
  - config.md
  - contracts.md
  - control-tags.md
  - dependabot.md
  - dependencies.md
  - design.md
  - docs.md
  - go-tidy.md
  - markdown.md
  - module-files.md
  - module-hierarchy.md
  - release.md
  - release-version.md
  - risk-catalog.md
  - risk-profile.md
  - specs.md
  - test-tags.md
  - version.md
