// File: go/cli/eac/impl/init/config_generator.go
package init

import (
	"fmt"
	"strings"
)

// ConfigGenerator defines the interface for generating repository configuration.
type ConfigGenerator interface {
	// Generate creates a repository.yml configuration from scan results.
	// Returns the YAML content as a string or an error if generation fails.
	Generate(workspaceRoot string, scanResult *ScanResult) (string, error)
}

// RuleBasedGenerator generates configuration using predefined rules and heuristics.
type RuleBasedGenerator struct{}

// NewRuleBasedGenerator creates a new rule-based configuration generator.
func NewRuleBasedGenerator() *RuleBasedGenerator {
	return &RuleBasedGenerator{}
}

// Generate implements ConfigGenerator for rule-based generation.
func (g *RuleBasedGenerator) Generate(workspaceRoot string, scanResult *ScanResult) (string, error) {
	var buf strings.Builder

	buf.WriteString("# EAC Repository Configuration\n")
	buf.WriteString("# Auto-generated from repository scan\n")
	buf.WriteString("# Generated by: r2r eac init --scan\n")
	buf.WriteString("\nrepository:\n")
	buf.WriteString("  name: project\n")
	buf.WriteString("  description: Auto-detected multi-module repository\n")
	buf.WriteString("\nmodules:\n")

	for _, mod := range scanResult.Modules {
		buf.WriteString(fmt.Sprintf("  - moniker: %s\n", strings.ToLower(strings.ReplaceAll(mod.Name, "_", "-"))))
		buf.WriteString(fmt.Sprintf("    description: %s module\n", mod.Language))
		buf.WriteString("    components:\n")
		buf.WriteString(fmt.Sprintf("      %s:\n", mod.Language))
		buf.WriteString(fmt.Sprintf("        root: %s\n", mod.Root))

		// Add type based on language defaults
		switch mod.Language {
		case "go":
			buf.WriteString("        type: service\n")
		case "python":
			buf.WriteString("        type: service\n")
		case "rust":
			buf.WriteString("        type: binary\n")
		case "typescript", "javascript":
			buf.WriteString("        type: app\n")
		case "dotnet":
			buf.WriteString("        type: webapi\n")
		case "java":
			buf.WriteString("        type: service\n")
		}
		buf.WriteString("\n")
	}

	return buf.String(), nil
}

// AIGenerator generates configuration using AI-powered analysis.
type AIGenerator struct {
	provider string
}

// NewAIGenerator creates a new AI-powered configuration generator.
func NewAIGenerator(provider string) *AIGenerator {
	return &AIGenerator{
		provider: provider,
	}
}

// Generate implements ConfigGenerator for AI-based generation.
func (g *AIGenerator) Generate(workspaceRoot string, scanResult *ScanResult) (string, error) {
	return GenerateConfig(workspaceRoot, scanResult, g.provider)
}

// GenerateWithFallback attempts to generate config with the primary generator,
// falling back to the fallback generator if the primary fails.
func GenerateWithFallback(workspaceRoot string, scanResult *ScanResult, primary, fallback ConfigGenerator) (string, error) {
	result, err := primary.Generate(workspaceRoot, scanResult)
	if err != nil {
		// Primary failed, try fallback
		return fallback.Generate(workspaceRoot, scanResult)
	}
	return result, nil
}
