name: "ci-src-commands (stage 1-6)"

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: ''
      ci_image:
        required: true
        type: string
        description: 'Full CI container image reference'
  workflow_dispatch:
    inputs:
      ref:
        required: false
        type: string
        default: ''
      sha:
        required: false
        type: string
        description: 'Commit SHA to test'
        default: ''
      ci_image:
        required: true
        type: string
        description: 'Full CI container image reference (e.g. ghcr.io/ready-to-release/go-bvt-image:2025.11.27)'

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.ci_image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Build Module
        working-directory: ./src/commands
        run: go run . build src-commands

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-src-commands
          path: out/build/src-commands/**

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.ci_image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-src-commands
          path: out/build/src-commands

      - name: Test Module
        working-directory: ./src/commands
        run: go run . test src-commands

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-src-commands
          path: out/test/**/src-commands/**
